spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jvm_ebook?allowPublicKeyRetrieval=true
    username: jvm
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 70
      minimum-idle: 50
      auto-commit: true
      read-only: true
  jpa:
    hibernate:
      ddl-auto: update
#    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
#    properties:
#      hibernate:
#        connection:
#          autocommit: true
#          provider_disables_autocommit: true
  application:
    name: jvm_ebook
#  threads:
#    virtual:
#      enabled: true
server:
  tomcat:
    threads:
      max: 200
